# Generated by Django 4.2.1 on 2023-05-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cotent', models.TextField()),
                ('rank', models.TextField()),
                ('price', models.CharField(max_length=250)),
                ('like', models.SmallIntegerField(blank=True, null=True)),
                ('iye', models.SmallIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('id_categoriya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='FlowersImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='flowers/')),
                ('id_flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flowers')),
            ],
        ),
        migrations.CreateModel(
            name='FlowersDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prcie', models.CharField(blank=True, max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('full_name_payee', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_payee', models.CharField(blank=True, max_length=250, null=True)),
                ('address_street_home', models.CharField(blank=True, max_length=250, null=True)),
                ('address_addition', models.CharField(blank=True, max_length=250, null=True)),
                ('date_delivery', models.DateField(blank=True, null=True)),
                ('time_delivery', models.TimeField(blank=True, null=True)),
                ('and_time', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_flowers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flowers')),
                ('id_type_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.typedelivery')),
            ],
        ),
        migrations.CreateModel(
            name='FlowersCommentVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ImageField(blank=True, null=True, upload_to='commit/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='video/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flowers')),
            ],
        ),
        migrations.AddField(
            model_name='flowers',
            name='id_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategoriya'),
        ),
    ]
