# Generated by Django 4.2.1 on 2023-05-20 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='flowers/'),
        ),
        migrations.CreateModel(
            name='FlowersCommentVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ImageField(blank=True, null=True, upload_to='commit/')),
                ('videos', models.FileField(blank=True, null=True, upload_to='video/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flowers')),
            ],
        ),
    ]
