# Generated by Django 4.2.1 on 2023-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('eye', models.SmallIntegerField()),
                ('like', models.SmallIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
