# Generated by Django 4.2.1 on 2023-05-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_flowers_img_flowerscommentvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FlowersDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prcie', models.CharField(blank=True, max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(max_length=250)),
                ('full_name_payee', models.CharField(max_length=250)),
                ('phone_payee', models.CharField(max_length=250)),
                ('address_street_home', models.CharField(max_length=250)),
                ('address_addition', models.CharField(max_length=250)),
                ('date_delivery', models.DateField()),
                ('time_delivery', models.TimeField()),
                ('and_time', models.TimeField()),
                ('comment', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('id_flowers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flowers')),
                ('id_type_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.typedelivery')),
            ],
        ),
    ]
