# Generated by Django 4.2.1 on 2023-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_typedelivery_flowersdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowersdelivery',
            name='address_addition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='address_street_home',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='and_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='date_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='full_name_payee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='phone_payee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='flowersdelivery',
            name='time_delivery',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
