# Generated by Django 4.2.1 on 2023-05-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_blogs_eye_alter_blogs_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowersimages',
            name='id_flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='admin_panel.flowers'),
        ),
    ]
