# Generated by Django 4.2.1 on 2023-05-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_flowersimages_id_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerscommentvideos',
            name='id_flowers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit', to='admin_panel.flowers'),
        ),
    ]
