# Generated by Django 4.2.1 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_flowerscommentvideos_id_flowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowersdelivery',
            name='id_flowers',
        ),
        migrations.AddField(
            model_name='flowersdelivery',
            name='id_flowers',
            field=models.ManyToManyField(blank=True, null=True, to='admin_panel.flowers'),
        ),
    ]
