# Generated by Django 4.2.1 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_flowersdelivery_id_flowers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowersdelivery',
            name='id_flowers',
            field=models.ManyToManyField(blank=True, to='admin_panel.flowers'),
        ),
    ]
