# Generated by Django 4.2.1 on 2023-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_flowersdelivery_id_flowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
