# Generated by Django 4.2.1 on 2023-06-27 05:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_categoriya_status_subcategoriya_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='cotent',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='rank',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
