# Generated by Django 4.2.1 on 2023-06-28 05:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_flowers_cotent_alter_flowers_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='cotent',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='rank',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
