# Generated by Django 4.2.1 on 2023-06-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_flowerscommentvideos_id_flowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerscommentvideos',
            name='videos',
        ),
    ]
