# Generated by Django 4.2.1 on 2024-03-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_size_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='admin_panel.flowers'),
        ),
    ]
